### ISSUE TITLE
 {Int,Hop,Bucket}Map should just return null value when item not matched.

### ISSUE THREAD

**Issue by madafoo** [G-M-twostay/Go-Utils#26]
Why does the Load() function in {Int,Hop,Bucket}Map allocate a new empty value each time when no match is found? If Load() is used in places where it is called frequently, it will result in a large number of useless memory allocation operations. I think might just return a  null as ChainMap Load() does is a better solution.

https://github.com/G-M-twostay/Go-Utils/blob/cbd9e91e39a445901eaaaca77207b9833eb952ab/Maps/IntMap/IntMap.go#L154

**Comment by G-M-twostay** [comment]
`new` doesn't necessarily allocate on heap, the compiler can perform escape analysis just fine with `*new(T)`. Also, this is the suggested way to get the zero value of an unknown generic type. https://stackoverflow.com/a/70589302/20161740, https://groups.google.com/g/golang-nuts/c/_ZiyS7KwxTI?pli=1. In fact, you can write a function that does something like `a:=*new(int)` and let compiler display optimizations, it'll show that this doesn't escape to heap.

Of course, I don't particularly like this method, and I hope Go will provide some other means of doing this.

> Why does the Load() function in {Int,Hop,Bucket}Map allocate a new empty value each time when no match is found? If Load() is used in places where it is called frequently, it will result in a large number of useless memory allocation operations. I think might just return a null as ChainMap Load() does is a better solution.
> 
> https://github.com/G-M-twostay/Go-Utils/blob/cbd9e91e39a445901eaaaca77207b9833eb952ab/Maps/IntMap/IntMap.go#L154

**Comment by madafoo** [comment]
Thanks, I have write a simple benchmark code and vierfy it.
